@echo off
set ORIGINAL_DIR=%CD%
set BAKED_DIR=%~dp0..\baked\%~n0.msvs
rmdir /S /Q "%BAKED_DIR%"
mkdir "%BAKED_DIR%"
chdir "%BAKED_DIR%"
cmake -G "Visual Studio 12 Win64" ^
	-DCMAKE_TARGET_BUILD_TOOL:STRING=msvs ^
	-DCMAKE_TARGET_OS:STRING=windows ^
	-DCMAKE_SHARED_LIBS_ALLOWED_ON_TARGET:BOOL=TRUE ^
	-DCMAKE_STATIC_LIBS_ALLOWED_ON_TARGET:BOOL=TRUE ^
	-DCMAKE_TARGET_CPU_ARCH:STRING=amd64 ^
	-DCMAKE_TARGET_CPU_ARCH_FAMILY:STRING=x86 ^
	-DCMAKE_COMPILER_FAMILY:STRING=msvc ^
	"%~dp0"
chdir %ORIGINAL_DIR%
