set(CMAKE_TARGET_OS macosx)
set(CMAKE_TARGET_CPU_ARCH intel)
set(CMAKE_TARGET_CPU_ARCH_FAMILY x86)
set(CMAKE_SHARED_LIBS_ALLOWED_ON_TARGET TRUE)
set(CMAKE_STATIC_LIBS_ALLOWED_ON_TARGET TRUE)
set(CMAKE_FAMILY clang)
set(CMAKE_ASM_FLAGS "-stdlib=libc++ -arch i386 -arch x86_64 -mmacosx-version-min=10.7 -fPIC")
set(CMAKE_C_FLAGS "-stdlib=libc++ -arch i386 -arch x86_64 -mmacosx-version-min=10.7 -fPIC")
set(CMAKE_CXX_FLAGS "-stdlib=libc++ -arch i386 -arch x86_64 -mmacosx-version-min=10.7 -fPIC")
set(CMAKE_OSX_ARCHITECTURES "i386;x86_64")
